kind: Service
apiVersion: v1
metadata:
  name: minecraft-service
spec:
  ports:
    - name: game
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30865
    - name: rcon
      protocol: TCP
      port: 25575
      targetPort: 25575
      nodePort: 30875
    selector:
      run: minecraft
    type: LoadBalancer